name: Deploy Terraform AWS

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform apply
        id: deploy
        working-directory: aws
        run: | 
          terraform init -backend-config=backend.conf
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
        env:
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
